name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SonarQube scanner
        uses: sonarsource/sonarqube-scan-action@v1
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar-host-url: http://10.40.3.102:9000
          sonar-project-key: my_project_key
          sonar-project-name: My Project
          sonar-project-version: 1.0

      - name: Run SonarQube scan
        run: sonar-scanner -Dsonar.host.url=http://10.40.3.102:9000 -Dsonar.login=$SONAR_TOKEN
