name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      # Add debug step to check URL
      - name: Debug SonarQube URL
        run: |
          # Extract domain from URL (remove protocol and any paths)
          SONAR_DOMAIN=$(echo ${{ secrets.SONAR_HOST_URL }} | sed -e 's|^[^/]*//||' -e 's|/.*$||')
          echo "Attempting to connect to domain: $SONAR_DOMAIN"
          
          # Try to resolve the domain
          host $SONAR_DOMAIN || echo "Failed to resolve domain"
          
          # Test connection
          timeout 10 bash -c "nc -zv $SONAR_DOMAIN 9000" || echo "Could not connect to port 9000"
        
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.scanner.connectTimeout=300
            -Dsonar.scanner.socketTimeout=300
            -X
